site_name: Neovim and Zellij Workshop
site_url: https://mydomain.org/mysite

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: false

nav:
  - Home: index.md
  - Vim Basics: vim-basics.md
  - Neovim and its Plugin Manager (Lazy): neovim-lazy.md
  - Zellij Basics: zellij-basics.md
  - Neovim and Zellij Together: neovim-and-zellij-together.md
